### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by fcfc2** [fflewddur/archivo#71] opened 2016-04-22 17:17 UTC
Thanks for some really great work to make things easy for folks.
I don't know how difficult it would be, but if possible, could you set some kind of trigger to start another download, before the first recording has completed processing.  There is considerable time lag now as multiple recordings are processed, and this would save the download time for all subsequent recordings to be processed.
If that is not possible, would it be possible to allow the program to be pointed at a folder which already contained Tivo recordings that had been downloaded by Tivo Desktop or whatever.

**Comment by fflewddur** [comment] 2016-04-22 17:23
You're welcome! It sounds like you're asking for the same feature as Issue #12; am I understanding you correctly? If so, I'll close this ticket as a duplicate of that one.

**Closed** 2016-05-22 18:14 UTC
