### ISSUE TITLE
archivo couldn't find any TiVos on your network...

### ISSUE THREAD

**Issue by rgonzale6** [fflewddur/archivo#59] opened 2016-04-12 05:29 UTC
Getting the above error - TiVo Premiere4 is on the same subnet as PC - pyTivo and Tivo Desktop successfully able to connect.  Firewall rules are allowing & tested with both windows  firewall and AVG disabled temporarily for testing.

Apart from this error - it would be nice if archivo could re-scan for a TiVo without having to close out and restart after you cancel out of the initial scan that fails.

Windows 10 machine - Nvidia Experience disabled and closed out.

00:28:12.680 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:28:13.077 [pool-4-thread-1] INFO  n.s.a.controller.UpdateCheckTask - Successfully fetched current_version.xml
00:28:13.109 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Update check: This is the latest version of Archivo (1.0.1)
00:28:13.436 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:28:13.442 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared
00:28:15.924 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - Setting status to 'Looking for TiVos...'
00:28:15.924 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Starting search for TiVo devices...
00:28:20.926 [pool-2-thread-1] INFO  n.s.archivo.net.TivoSearchTask - Found instances: []
00:28:20.926 [JavaFX Application Thread] INFO  net.straylightlabs.archivo.Archivo - TaskStatus cleared

**Comment by fflewddur** [comment] 2016-04-13 02:55
Hi @rgonzale6, thanks for reporting this. Do you have VMware installed, by chance? I recently discovered that the virtual network interfaces it adds prevent Archivo from being able to find TiVos; disabling the virtual adapters will let you temporarily work around the issue while I figure out the cause of the problem.

**Comment by TivoMan** [comment] 2016-04-19 02:35
Same here. It can't find any Tivos on my network. {Macbook air, OS 10.10.5, Roamio}. The previous version could find it; this one can't. I don't have VMware (or anything of the sort) installed.

**Comment by fflewddur** [comment] 2016-04-21 05:07
@TivoMan  and @rgonzale6 , I think I have a fix for this. Could you try downloading the attached hola-0.1.3.jar.zip file, unzip it, and replace the hola-0.1.3.jar file in C:\Program Files (x86)\Archivo with it? On a Mac, you'll need to right-click /Applications/Archivo, select "Show Package Contents", and navigate to Contents->Java to find the place to paste this file. Let me know if it helps.
[hola-0.1.3.jar.zip](https://github.com/fflewddur/archivo/files/229219/hola-0.1.3.jar.zip)

**Comment by dcbarry** [comment] 2016-04-21 19:14
@fflewddur :   I tried using the updated jar within version 1.0.1 under OS X 10.11.3 

Unfortunately, It still only sees my newest roamio, and not my two older boxes (HDs)

**Comment by fflewddur** [comment] 2016-04-21 19:33
@dcbarry Thanks for the report! Archivo only supports Premier, Roamio, and Bolt models,so if you're referring to the Series 3 HD units, it's expected that those will not show in the list of available TiVos.

**Comment by dcbarry** [comment] 2016-04-21 21:46
Oh, fiddlesticks! I probably missed that in your README document.

Just curious, why the distinction? Is this a MPEG TS versus PS il issue

**Comment by fflewddur** [comment] 2016-04-21 22:32
The older models don't support the RPC interface Archivo uses to communicate with TiVo devices.

**Comment by TivoMan** [comment] 2016-04-22 03:41
@fflewddur : That did it! I was able to see and download/ archive the shows; it even downloaded shows the other apps couldn't. Thanks.

**Comment by fflewddur** [comment] 2016-04-22 03:43
@TivoMan Fantastic, thanks for letting me know! I'll roll this out in a new Archivo release this weekend or next.

**Comment by fflewddur** [comment] 2016-05-01 21:16
@rgonzale6 I just released an update that should resolve this issue. Can you let me know if it works for you? The download is available at https://github.com/fflewddur/archivo/releases/tag/v1.0.2

**Comment by rgonzale6** [comment] 2016-05-06 14:28
Same issue unfortunately - even after the 1.0.3 update.  My Tivo is on my same subnet and it's findable by Tivo Desktop and kmttg so I don't think it's a network problem.

**Comment by rgonzale6** [comment] 2016-05-06 14:40
Working now, thanks!  (not sure if it was the file replacement or 1.0.3 update)

**Closed** 2016-05-06 14:42 UTC
Labels: bug, high priority

**Comment by MikeRich88** [comment] 2016-10-27 07:22
Is the HTTP interface provided by Series3 unsuitable? I mean it would have to be scraped and all of that but I think we can assume that the format is not going to change. 

So while writing this I did research and there is also an HTTP interface that seems to provide a lot more data in XML. http://tivopod.sourceforge.net/tivohomemedia.pdf

Looking at the source code for Archivo it looks like support for Series3 (maybe in a more limited fashion) could be added.

**Comment by fflewddur** [comment] 2016-10-30 23:48
All of the network code is structured around the RPC interface. If someone writes a clean patch that adds support for Series3 units, I wouldn't reject it, but I'm not interested in doing this myself.
